#!/bin/sh
set -e

EXIT_OK=0
EXIT_USAGE=1
EXIT_FAILURE=2
# EXIT_RETRY=3

BREW_INSTALL_OPTIONS=
BREW_REMOVE_OPTIONS=

usage() {
    cat << EOF
USAGE
    $0 plugin for thin-edge.io

    $0 <COMMAND> [MODULE_NAME] [--module-version [VERSION]] [--file [FILE]]

    $0 list
    $0 prepare
    $0 install <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 remove <MODULE_NAME> [--module-version [VERSION]]
    $0 finalize
EOF
}

MODULE_NAME=
MODULE_VERSION=
FILE=

log() { echo "$@" >&2; }

if [ $# -lt 1 ]; then
    log "Invalid number of positional arguments"
    usage
    exit "$EXIT_USAGE"
fi

# argument parsing
while [ $# -gt 0 ]; do
  case "$1" in
    --module-version)
        MODULE_VERSION="$2"
        shift
        ;;
    --file)
        FILE="$2"
        shift
        ;;
    -h|--help)
        usage
        exit "$EXIT_USAGE"
        ;;
    --*|-*)
        log "Unknown option $1"
        exit "$EXIT_USAGE"
        ;;
    *)
        if [ -z "$COMMAND" ]; then
            COMMAND="$1"
        elif [ -z "$MODULE_NAME" ]; then
            MODULE_NAME="$1"
        fi
      ;;
  esac
  shift
done

command_exists() {
    command -V "$1" >/dev/null 2>&1
}

case "$COMMAND" in
    prepare)
        ;;
    list)
        if ! command_exists brew; then
            log "The brew command was not found! This is very unexpected" >&2
            exit "$EXIT_USAGE"
        fi

        brew list --versions | tr ' ' '\t'
        ;;
    install)
        if [ -n "$FILE" ]; then
            log "Installing brew from file is not supported: FILE=$FILE"
            exit "$EXIT_FAILURE"
        else
            MODULE_COMMAND=
            if [ -n "$MODULE_VERSION" ] && [ "$MODULE_VERSION" != "latest" ]; then
                MODULE_COMMAND="$MODULE_NAME@$MODULE_VERSION"
            else
                MODULE_COMMAND="$MODULE_NAME@$MODULE_VERSION"
            fi

            log "Pouring brew (by name): brew install $MODULE_COMMAND $BREW_INSTALL_OPTIONS"
            # shellcheck disable=SC2086
            brew install "$MODULE_COMMAND" $BREW_INSTALL_OPTIONS || exit "$EXIT_FAILURE"
        fi
        ;;
    remove)
        # Removing
        # shellcheck disable=SC2086
        brew uninstall "$MODULE_NAME" $BREW_REMOVE_OPTIONS || exit "$EXIT_FAILURE"
        ;;
    update-list)
        # Not supported, use remove install and remove instead
        exit "$EXIT_USAGE"
        ;;
    finalize)
        ;;
    *)
        log "Unsupported command: $COMMAND"
        exit 1
        ;;
esac

exit "$EXIT_OK"
